Controllers/LiveController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.Drawing;
using Syncfusion.Presentation;
using System.Globalization;
using VVA.ITS.WebApp.Interfaces;
using VVA.ITS.WebApp.Models;
using VVA.ITS.WebApp.Services;
using VVA.ITS.WebApp.Services.Helps;

namespace VVA.ITS.WebApp.Controllers
{
   
    public class LiveController : Controller
	{
        private readonly IDataxe? dataxe;
        private readonly UserManager<AppUser> userManager;
        private readonly IPdfService _pdfService;
        private readonly IWebHostEnvironment env;
        public LiveController(UserManager<AppUser> userManager, IDataxe dataxe, IPdfService pdfService, IWebHostEnvironment env)
		{
			this.dataxe = dataxe;
            this.userManager = userManager;
            this._pdfService = pdfService;
            this.env = env;
        }
        public async Task<IActionResult> Index()
		{
			try
			{
                AppUser user = await userManager.GetUserAsync(HttpContext.User);
                if (user == null) return RedirectToAction("Login", "Account");
                var Dataxe = await this.dataxe.GetAllDataXe();
                return View(Dataxe);
            }
            catch (Exception) { }
            return View();
        }
        [HttpPost]
		public async Task<List<DataXe>> SeachWeight([FromBody] SeachVehicles seachVehicles)
		{
			try
			{
                var data = await dataxe.SeachWeight(seachVehicles);
                return data;
            }
            catch (Exception) { }
            return null;
		}

        [HttpPost]
        public async Task<DataXe> SeachWeightById(string id)
        {
            try
            {
                var data = await dataxe.SeachWeightById(id);
                if (data != null)
                {
                    data.Hinhtruoc = clsHelps.GetRelativePath1(data.Hinhtruoc);
                    data.Hinhsau = clsHelps.GetRelativePath1(data.Hinhsau);
                }
                return data;
            }
            catch (Exception) { }
            return null;
        }
        [HttpPost]
        public async  Task<IActionResult>UpdateImage(IFormFileCollection files,string id)
        {
            try
            {
                var data = await dataxe.SeachWeightById(id);
                if (data==null) return BadRequest();

                if(data.Hinhsau.Length> 0 || data.Hinhtruoc.Length>0)
                {
                    return BadRequest();
                }
                string filePath = Path.Combine(this.env.ContentRootPath, "wwwroot", "upload",DateTime.Now.ToString("ddMMyy"));
                if (!Directory.Exists(filePath))
                {
                    Directory.CreateDirectory(filePath);
                }
                int i = 0;
                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        var path = Path.Combine(filePath, file.FileName);

                        if (!System.IO.File.Exists(path))
                        {
                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                await file.CopyToAsync(stream);
                            }
                            if (i == 0)
                            {
                                data.Hinhtruoc = path;
                            }
                            if (i == 1)
                            {
                                data.Hinhsau = path;
                            }
                            i++;
                        }
                    }
                }
                bool update = await dataxe.Update(data);
                if (update)
                {
                    return Ok("Câp nhật thành công.");
                }
            }
            catch (Exception) { }
            return BadRequest();
        }
       
        [HttpPost]
        public async Task<List<string>> UpdateImageFile(IFormFileCollection files)
        {
            List<string> data = new List<string>();
            try
            {
                string filePath = Path.Combine(this.env.ContentRootPath, "wwwroot", "upload", DateTime.Now.ToString("ddMMyy"));
                if (!Directory.Exists(filePath))
                {
                    Directory.CreateDirectory(filePath);
                }
                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        var path = Path.Combine(filePath, file.FileName);
                        if(!System.IO.File.Exists(path)) 
                        {
                            data.Add(path);
                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                await file.CopyToAsync(stream);
                            }
                        }
                    }
                }
               return data;
            }
            catch (Exception) { }
            return data;
        }
        [HttpPost]
        public async Task<IActionResult> ExportExel([FromBody] SeachVehicles seach)
        {
            try
            {
                AppUser user = await userManager.GetUserAsync(HttpContext.User);
                if (user != null)
                {
                    List<DataXe> data = await SeachWeight(seach);
                    if (user.UserName == "svtt1")
                    {
                        if (data != null && data.Count > 0)
                        {
                            string filePath = Path.Combine(env.ContentRootPath, "wwwroot", "exel", "phieucanxe.xlsx");

                            using (XLWorkbook wb = new XLWorkbook(filePath))
                            {
                                IXLWorksheet worksheet = wb.Worksheet(1);

                                if (worksheet != null)
                                {
                                    int row = 11; // Dòng bắt đầu ghi dữ liệu
                                    int i = 1;
                                    foreach (var vehicle in data)
                                    {
                                        //STT
                                        worksheet.Range($"A{row}:A{row + 1}").Merge();
                                        worksheet.Cell(row, 1).Value = i;
                                        i++;
                                        // Loại xe
                                        worksheet.Cell(row, 2).Value = clsHelps.GetVehicleTypeString((int)vehicle.Loaixe);
                                        worksheet.Range($"B{row}:B{row + 1}").Merge();

                                        // Kí hiệu
                                        worksheet.Cell(row, 3).Value = $"({vehicle.Loaixe})";
                                        worksheet.Range($"C{row}:C{row + 1}").Merge();

                                        // Biển kiểm soát
                                        worksheet.Cell(row, 4).Value = vehicle.Biensotruoc;
                                        worksheet.Range($"D{row}:D{row + 1}").Merge();

                                        // Số trục xe
                                        worksheet.Cell(row, 5).Value = 0;
                                        worksheet.Cell(row + 1, 5).Value = "K/cách trục";

                                        // Tải trọng trục
                                        worksheet.Cell(row, 6).Value = vehicle.Taitrongtruc1;
                                        worksheet.Cell(row, 7).Value = vehicle.Taitrongtruc2;
                                        worksheet.Cell(row, 8).Value = vehicle.Taitrongtruc3;
                                        worksheet.Cell(row, 9).Value = vehicle.Taitrongtruc4;
                                        worksheet.Cell(row, 10).Value = vehicle.Taitrongtruc5;
                                        worksheet.Cell(row, 11).Value = vehicle.Taitrongtruc6;

                                        worksheet.Cell(row + 1, 6).Value = 0;
                                        worksheet.Cell(row + 1, 7).Value = 0;
                                        worksheet.Cell(row + 1, 8).Value = 0;
                                        worksheet.Cell(row + 1, 9).Value = 0;
                                        worksheet.Cell(row + 1, 10).Value = 0;
                                        worksheet.Cell(row + 1, 11).Value = 0;

                                        // Tải trọng từng cụm trục
                                        worksheet.Range($"L{row}:L{row + 1}").Column(1).Merge();
                                        worksheet.Range($"M{row}:M{row + 1}").Column(1).Merge();
                                        worksheet.Range($"N{row}:N{row + 1}").Column(1).Merge();
                                        worksheet.Range($"O{row}:O{row + 1}").Column(1).Merge();
                                        worksheet.Range($"P{row}:P{row + 1}").Column(1).Merge();
                                        worksheet.Range($"Q{row}:Q{row + 1}").Column(1).Merge();
                                        worksheet.Range($"R{row}:R{row + 1}").Column(1).Merge();
                                        worksheet.Range($"S{row}:S{row + 1}").Column(1).Merge();

                                        worksheet.Cell(row, 12).Value = vehicle.TLtruc1;
                                        worksheet.Cell(row, 13).Value = vehicle.TLtruc2;
                                        worksheet.Cell(row, 14).Value = vehicle.TLtruc3;
                                        worksheet.Cell(row, 15).Value = vehicle.TTLtruc;

Views/Shared/_CommonCSS.cshtml
    <!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="~/css/google.font.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="~/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="~/css/adminlte.min.css">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
<!-- Customed site -->
<link rel="stylesheet" href="~/css/site.css">

Views/Shared/_CommonScript.cshtml
<!-- jQuery -->
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- jQuery Validation -->
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<!-- jQuery Validation Unobtrusive -->
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<!-- AdminLTE App -->
<script src="~/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
@* <script src="~/js/theme.customized.js"></script> *@

Views/Shared/_Footer.cshtml
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2023-2028 <a href="https://www.facebook.com/huy02092001" target="_blank">Viet Vision Automation</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.1.0
    </div>
</footer>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @await Html.PartialAsync("_CommonCSS")
    @await RenderSectionAsync("ExtraCSS", required: false)
</head>
<body class="hold-transition sidebar-mini sidebar-collapse layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        @await Html.PartialAsync("_Preloader")

        <!-- Navbar -->
       @*  @await Html.PartialAsync("_Navbar") *@
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        @await Html.PartialAsync("_Sidebar")


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
          @*   @await RenderSectionAsync("ContentHeader", required: false) *@
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content" style="margin-left:170px">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        @await Html.PartialAsync("_Footer")

      
    </div>
    <!-- ./wrapper -->
    @await Html.PartialAsync("_CommonScript")
    @await RenderSectionAsync("ExtraScripts", required: false)
</body>
</html>

Views/Shared/_Menu.cshtml
<nav class="mt-2">
    <ul id="sidebarMenu" class="nav nav-pills nav-sidebar flex-column text-light" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
        <li class="nav-item">
            <button type="button" class="btn" style="margin-left: 30px;">
                <a href="http://vva.com.vn">
                    <img src="~/img/VVA_LOGO.gif" alt="Viet Vision Automation" class="brand-image img-circle elevation-3" style="opacity: .8;">
                    <span class="brand-text font-weight-light">Vision ITS</span>
                </a>
            </button>
        </li>
        <li class="nav-item border border-primary">
            <button type="button" class="btn">
                <a id="menuDashboard" asp-controller="Dashboard" asp-action="Thongke" class="nav-link">
                    <span class="icon-text-container">
                        <i class="fas fa-home"></i>
                        <span>ITS Dashboard</span>
                    </span>
                </a>
            </button>
        </li>
        <li class="nav-item border border-primary">
            <button type="button" class="btn">
                <a id="menuLiveData" asp-controller="Dashboard" asp-action="Index" class="nav-link">
                    <span class="icon-text-container">
                        <i class="fas fa-weight"></i>
                        <span>Dữ liệu trực tuyến</span>
                    </span>
                </a>
            </button>
        </li>
        <li class="nav-item border border-primary">
            <button type="button" class="btn">
                <a id="menuLiveData"
                   href="@Url.Action("Indexfind", "Dashboard", new { page = 1, pageSize = 10, speedsend = 0, directionsend = 0, platecolor = 0, vehiclecolor = 0, vehiclebrand = 0, platesend = "", starttime = "", endtime = "", VehicleType = 0 })"
                   class="nav-link">
                    <span class="icon-text-container">
                        <i class="fas fa-weight"></i>
                        <span>Tra cứu phương tiện</span>
                    </span>
                </a>
            </button>
        </li>
        @if (User.Identity.Name != "svtt")
        {
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuLiveData" asp-controller="Dashboard" asp-action="Maps" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fas fa-weight"></i>
                            <span>Bản đồ số GIS Maps</span>
                        </span>
                    </a>
                </button>
            </li>
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuLiveData" asp-controller="Live" asp-action="Index" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fas fa-weight"></i>
                            <span>Dữ liệu cân động</span>
                        </span>
                    </a>
                </button>
            </li>
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuLiveData" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fas fa-weight"></i>
                            <span>Thống kê cân động</span>
                        </span>
                    </a>
                </button>
            </li>
        }
        @if (User.Identity.Name == "Admin")
        {
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuRegisterUser" asp-controller="Account" asp-action="Register" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fa fa-user-plus" style="color: green;"></i>
                            <span>Thêm mới người dùng</span>
                        </span>
                    </a>
                </button>
            </li>
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuDeleteUser" asp-controller="Account" asp-action="Index" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fas fa-user-times" style="color: red;"></i>
                            <span>Xóa bỏ người dùng</span>
                        </span>
                    </a>
                </button>
            </li>
            <li class="nav-item border border-primary">
                <button type="button" class="btn">
                    <a id="menuListRole" asp-controller="Role" asp-action="Index" class="nav-link">
                        <span class="icon-text-container">
                            <i class="fa fa-hospital-user" style="color: yellow;"></i>
                            <span>Danh sách phân quyền</span>
                        </span>
                    </a>
                </button>
            </li>
        }
        <li class="nav-item border border-primary">
            <button type="button" class="btn">
                <a id="menuDashboard" asp-controller="Account" asp-action="Logout" class="nav-link">
                    <span class="icon-text-container">
                        <i class="fas fa-arrow-alt-circle-right"></i>
                        <span>Đăng xuất</span>
                    </span>
                </a>
            </button>
        </li>
    </ul>
</nav>
<style>
    .icon-text-container {
        display: flex;
        align-items: center; /* Align items vertically */
    }

        .icon-text-container i {
            margin-right: 12px; /* Adjust the space between the icon and text */
        }
</style>

Views/Shared/_Navbar.cshtml
<nav class="navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    @* <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul> *@

    <!-- Right navbar links -->
    @* <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> *@

        <!-- Messages Dropdown Menu -->
@*        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>*@
        <!-- Notifications Dropdown Menu -->
 @*       <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>*@
        @* <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li> *@
   @*  </ul> *@
</nav>

Views/Shared/_Preloader.cshtml
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="~/img/vva_logo_transparent.png" alt="VVA Logo" height="60" width="60">
</div>

Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4 sidebar-no-expand" style="width:240px">

    <!-- Sidebar -->
    <div class="sidebar ">
        <!-- Sidebar Menu -->
        @await Html.PartialAsync("_Menu")
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>